#!/bin/bash

# ---------------------------
#      variables
# ---------------------------

declare -r dataPath='./src/Data/index.js'
declare -r endpoint='http://localhost:5001'

# ---------------------------
#      functions
# ---------------------------

## display help
displayHelp(){
    echo "Usage: $0 [pre|post]"
    echo
    echo "  Options:"
    echo "    pre        remove endpoint from Data variables"
    echo "    post       insert endpoint to Data variables"
    echo

    exit 1
}

## multi-lines
# Mac
rmend_mac() {
  sed -i '' "
  /baseURL:/ {
    s|$endpoint||
  }" $dataPath
}

insend_mac() {
  sed -i '' "
  /baseURL:/ {
    s|''|'$endpoint'|
  }" $dataPath
}

# Linux
rmend_li() {
  sed -i "
  /baseURL:/ {
    s|$endpoint||
  }" $dataPath
}

insend_li() {
  sed -i "
  /baseURL:/ {
    s|''|'$endpoint'|
  }" $dataPath
}

# ---------------------------
#      main
# ---------------------------

main() {
  # declare local os suffix
  local ossuf

  # set os suffix
  if [ "$(uname)" = "Darwin" ]; then
    ossuf=mac
  else
    ossuf=li
  fi

  case $1 in
    'pre' )
      rmend_$ossuf
      exit
    ;;
    'post' )
      insend_$ossuf
      exit
    ;;
    '-t' )
      # testMultiRemove
      # testMultiInsert
      displayHelp
      exit
    ;;
    * )
      displayHelp
    ;;
  esac
}

main $@
