# List of locations *that can be used to make recommendations*
# (Other locations are valid, but can't be suggested)

locations = [
    'Annenberg Center',
    'BRB Auditorium',
    'Barchi Library',
    'Benjamin Franklin Room',
    'Blockley Hall',
    'Bodek Lounge',
    'Brubaker Auditorium',
    'Classical Studies Lounge',
    'Cohen Hall',
    'College Green',
    'DRL',
    'David Rittenhouse Lab',
    'Fireside Lounge',
    'Fisher Fine Arts Library',
    'Fisher-Bennett Hall',
    'Fitts Auditorium',
    'Goddard Labs',
    'Hayden Hall',
    'Houston Hall',
    'Huntsman Hall',
    'International House',
    'Irvine Auditorium',
    'John Morgan Building',
    'Kelly Writers House',
    'Kleinman Center',
    'Kroiz Gallery',
    'Levine Hall',
    'Lightbox Film Center',
    'Locust Walk',
    'McNeil Building',
    'Montgomery Theater',
    'Montgomery Theatre',
    'Morgan Building',
    'Morgan Fine Arts Building',
    'Music Building',
    'National Mechanics',
    'PCPSE',
    'Parkway Central Library',
    'Penn Book Center',
    'Penn Museum',
    'Perelman Center for Political Science',
    'Rainey Auditorium',
    'Rubenstein Auditorium',
    'Silverstein Forum',
    'Slought',
    'Smilow Center',
    'Solomon Building',
    'Stiteler Hall',
    'Suzanne Roberts Theatre',
    'Tedori Family Auditorium',
    'The Ambler Theater',
    'The Goodhand Room',
    'Towne',
    'Van Pelt Library',
    'Williams Hall',
    'Wu and Chen Auditorium'
]
